title = "Michiel van der Winden's blog"
baseURL = 'https://mvdwinden.nl/blog/'

# This is what goes in <html lang="">
languageCode = 'en-us'

theme = "hugo-awesome"

# This defines how dates are formatted
defaultContentLanguage = "en-us"

# Enable emojis globally
enableEmoji = true
ignoreErrors = [
    "additional-script-loading-error",
] # ignore error of loading additional scripts.

[markup]
    [markup.highlight]
        noClasses = false
    [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
        startLevel = 2  
        endLevel = 4    
        ordered = false

[menu]
    [[menu.main]]
        pageRef = "posts"
        name = 'Posts'
        url = '/'
        weight = 20
    [[menu.main]]
        pageRef = "about"
        name = 'About'
        url = '/about/'
        weight = 30

[params]
    sitename = "Michiel van der Winden's blog"
    defaultColor = "dark"
    description = "Ex-Integration Developer gone AWS Cloud Consultant. Loves refactoring and improving performance. Containerizes everything. Writes about things he finds interesting or funny."
    mainSections = ['posts']
    toc = false
    goToTop = true
    rssFeedDescription = "full"

[params.author]
    avatar = "michiel.png" # put the file in assets folder; also ensure that image has same height and width
    # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
    intro = "Michiel van der Winden"
    name = "Michiel van der Winden"
    description = "Ex-Integration Developer gone AWS Cloud Consultant. Loves refactoring and improving performance. Containerizes everything. Writes about things he finds interesting or funny."

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/MichielVanDerWinden"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/michiel-van-der-winden-8512325b/"

[outputs]
    home = ['html', 'rss']
    section = ['html', 'rss']
    taxonomy = ['html']
    term = ['html']